import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS } from '../../constants/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FF',
  },
  gradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(91, 155, 255, 0.20)',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F8FF',
  },
  loadingText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    marginTop: SIZES.md,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.xl,
  },
  heroCard: {
    borderRadius: 22,
    padding: SIZES.lg,
    marginTop: SIZES.md,
    marginBottom: SIZES.md,
    shadowColor: '#0D3B8E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.md,
  },
  heroTitle: {
    ...FONTS.h3,
    color: COLORS.white,
    fontWeight: '700',
  },
  heroSubtitle: {
    ...FONTS.caption,
    color: '#DDEBFF',
  },
  heroAddButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#E2EEFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroStatItem: {
    alignItems: 'center',
  },
  heroStatValue: {
    ...FONTS.h4,
    color: COLORS.white,
    fontWeight: '800',
  },
  heroStatLabel: {
    ...FONTS.small,
    color: '#DDEBFF',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingHorizontal: SIZES.md,
    gap: SIZES.sm,
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    ...FONTS.body,
    paddingVertical: SIZES.md,
    color: COLORS.text,
  },
  filtersContainer: {
    marginTop: SIZES.md,
    maxHeight: 50,
  },
  filtersContent: {
    gap: SIZES.sm,
  },
  filterChip: {
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.sm,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#DDE6F6',
  },
  filterChipActive: {
    backgroundColor: '#1D4ED8',
    borderColor: '#1D4ED8',
  },
  filterChipText: {
    ...FONTS.caption,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  filterChipTextActive: {
    color: COLORS.white,
  },
  resultsCounter: {
    paddingVertical: SIZES.md,
  },
  resultsText: {
    ...FONTS.caption,
    color: '#6C7891',
    fontWeight: '600',
  },
  userCard: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: SIZES.md,
    marginBottom: SIZES.md,
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  userCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  userCardInfo: {
    flex: 1,
    marginLeft: SIZES.md,
  },
  userName: {
    ...FONTS.bodyBold,
    fontSize: 16,
    color: '#1B284A',
    marginBottom: SIZES.xs,
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  roleText: {
    ...FONTS.small,
    fontWeight: '700',
  },
  userCardDetails: {
    gap: SIZES.xs,
    marginBottom: SIZES.sm,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.sm,
  },
  detailText: {
    ...FONTS.caption,
    color: '#62708D',
    flex: 1,
  },
  userCardActions: {
    flexDirection: 'row',
    gap: SIZES.sm,
    paddingTop: SIZES.sm,
    borderTopWidth: 1,
    borderTopColor: '#EDF2FB',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  actionButtonText: {
    ...FONTS.caption,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: SIZES.xxl,
  },
  emptyStateText: {
    ...FONTS.h4,
    color: '#54627E',
    marginTop: SIZES.lg,
  },
  emptyStateSubtext: {
    ...FONTS.caption,
    color: COLORS.textLight,
    marginTop: SIZES.xs,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 20, 38, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    paddingTop: SIZES.lg,
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#D5DFEF',
    alignSelf: 'center',
    marginBottom: SIZES.sm,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.md,
    borderBottomWidth: 1,
    borderBottomColor: '#E8EEF8',
  },
  modalTitle: {
    ...FONTS.h4,
    color: '#1A2752',
    fontWeight: '700',
  },
  modalSubtitle: {
    ...FONTS.small,
    color: '#6A7895',
    marginTop: 2,
    maxWidth: 260,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F7FF',
  },
  modalScroll: {
    paddingHorizontal: SIZES.lg,
  },
  formSection: {
    marginTop: SIZES.lg,
  },
  formCard: {
    backgroundColor: '#F9FBFF',
    borderWidth: 1,
    borderColor: '#E4ECFA',
    borderRadius: 14,
    padding: SIZES.md,
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
    marginBottom: SIZES.sm,
  },
  formSectionIcon: {
    width: 24,
    height: 24,
    borderRadius: 7,
    backgroundColor: '#EAF1FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formSectionTitle: {
    ...FONTS.bodyBold,
    color: '#1A2752',
    marginBottom: SIZES.xs,
  },
  inputLabel: {
    ...FONTS.caption,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SIZES.sm,
  },
  rolePicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SIZES.sm,
  },
  roleOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DDE6F6',
    backgroundColor: COLORS.white,
  },
  roleOptionActive: {
    backgroundColor: '#1D4ED8',
    borderColor: '#1D4ED8',
  },
  roleOptionText: {
    ...FONTS.caption,
    fontWeight: '600',
    color: COLORS.text,
  },
  roleOptionTextActive: {
    color: COLORS.white,
  },
  modalActions: {
    flexDirection: 'row',
    gap: SIZES.md,
    marginTop: SIZES.xl,
    paddingTop: SIZES.md,
    borderTopWidth: 1,
    borderTopColor: '#E8EEF8',
    backgroundColor: COLORS.white,
  },
});

export default styles;
