import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS } from '../../constants/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FF',
  },
  gradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(91, 155, 255, 0.20)',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F8FF',
  },
  loadingText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    marginTop: SIZES.md,
  },
  heroCard: {
    borderRadius: 22,
    padding: SIZES.lg,
    marginHorizontal: SIZES.lg,
    marginTop: SIZES.md,
    marginBottom: SIZES.md,
    shadowColor: '#0D3B8E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  heroTitle: {
    ...FONTS.h4,
    color: COLORS.white,
    fontWeight: '700',
  },
  heroSubtitle: {
    ...FONTS.caption,
    color: '#DDEBFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#E2EEFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthInfo: {
    alignItems: 'center',
  },
  monthText: {
    ...FONTS.h4,
    fontWeight: '700',
    color: COLORS.white,
  },
  todayButton: {
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.xs / 2,
    borderRadius: 999,
    backgroundColor: '#E2EEFF',
  },
  todayButtonText: {
    ...FONTS.small,
    color: '#0D3B8E',
    fontWeight: '700',
  },
  legend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: SIZES.lg,
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.md,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    ...FONTS.small,
    color: '#62708D',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SIZES.lg,
  },
  weekDaysContainer: {
    flexDirection: 'row',
    marginBottom: SIZES.sm,
  },
  weekDayCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: SIZES.sm,
  },
  weekDayText: {
    ...FONTS.caption,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: SIZES.xs,
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  dayCell: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    padding: SIZES.xs,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.radiusSmall,
    position: 'relative',
  },
  dayCellToday: {
    backgroundColor: '#EAF1FF',
  },
  dayCellEmpty: {
    opacity: 0,
  },
  dayNumber: {
    ...FONTS.body,
    fontWeight: '600',
    color: '#1B284A',
  },
  dayNumberToday: {
    color: COLORS.primary,
    fontWeight: '800',
  },
  activityCount: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: COLORS.info,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  activityCountText: {
    ...FONTS.small,
    fontSize: 10,
    color: COLORS.white,
    fontWeight: '700',
  },
  statusIndicator: {
    position: 'absolute',
    bottom: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  monthSummary: {
    marginTop: SIZES.xl,
  },
  summaryTitle: {
    ...FONTS.h4,
    fontWeight: '700',
    marginBottom: SIZES.md,
    color: '#1A2752',
  },
  summaryCards: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SIZES.md,
  },
  summaryCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: SIZES.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryValue: {
    ...FONTS.h2,
    fontWeight: '800',
    marginVertical: SIZES.xs,
  },
  summaryLabel: {
    ...FONTS.caption,
    color: '#62708D',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 20, 38, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    paddingTop: SIZES.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    ...FONTS.h3,
    fontWeight: '700',
  },
  modalScroll: {
    paddingHorizontal: SIZES.lg,
    paddingTop: SIZES.md,
  },
  modalActivity: {
    marginBottom: SIZES.md,
  },
});

export default styles;
