import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS } from '../../../constants/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FF',
  },
  backgroundGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(91, 155, 255, 0.20)',
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SIZES.lg,
    paddingTop: SIZES.lg,
    paddingBottom: SIZES.md,
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#E6EEFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: SIZES.md,
  },
  headerTitle: {
    ...FONTS.bodyBold,
    fontSize: 17,
    color: '#16213D',
  },
  headerSubtitle: {
    ...FONTS.small,
    color: '#5F6C86',
    textTransform: 'capitalize',
  },
  notificationButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#FFF7E7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: 2,
    right: 2,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    backgroundColor: COLORS.warning,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: COLORS.white,
    fontSize: 10,
    fontWeight: '700',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.xxl,
  },
  heroCard: {
    borderRadius: 24,
    padding: SIZES.lg,
    marginBottom: SIZES.lg,
    shadowColor: '#0D3B8E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SIZES.lg,
  },
  heroIdentity: {
    flex: 1,
    marginRight: SIZES.md,
  },
  heroGreeting: {
    ...FONTS.small,
    color: '#D7E7FF',
    marginBottom: 2,
  },
  heroName: {
    ...FONTS.h3,
    color: COLORS.white,
    fontSize: 24,
    lineHeight: 30,
    marginBottom: SIZES.sm,
  },
  heroRolePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  heroRoleText: {
    ...FONTS.small,
    color: '#E7F1FF',
    fontWeight: '600',
  },
  heroBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroDateLabel: {
    ...FONTS.small,
    color: '#BFDAFF',
  },
  heroDate: {
    ...FONTS.bodyBold,
    color: '#FFFFFF',
    textTransform: 'capitalize',
  },
  heroCta: {
    backgroundColor: '#E2EEFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroCtaText: {
    ...FONTS.caption,
    color: '#0D3B8E',
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SIZES.lg,
  },
  statCard: {
    width: '48%',
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: SIZES.md,
    marginBottom: SIZES.md,
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 3,
  },
  statIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  statValue: {
    ...FONTS.h3,
    fontSize: 22,
    color: '#1A2752',
    marginBottom: 2,
  },
  statLabel: {
    ...FONTS.caption,
    color: '#606E8B',
    marginBottom: 2,
  },
  statHelper: {
    ...FONTS.small,
    fontWeight: '600',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SIZES.md,
    marginTop: SIZES.xs,
  },
  sectionTitle: {
    ...FONTS.h5,
    color: '#1A2752',
    fontWeight: '700',
  },
  sectionAction: {
    ...FONTS.caption,
    color: '#1D62D2',
    fontWeight: '700',
  },
  patientList: {
    marginBottom: SIZES.lg,
  },
  patientCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: SIZES.md,
    marginBottom: SIZES.md,
    borderWidth: 1,
    borderColor: '#EDF2FB',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  patientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  patientInfo: {
    flex: 1,
    marginHorizontal: SIZES.sm,
  },
  patientName: {
    ...FONTS.bodyBold,
    color: '#1B284A',
    marginBottom: 2,
  },
  patientDetail: {
    ...FONTS.small,
    color: '#6C7891',
  },
  priorityPill: {
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  priorityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  priorityText: {
    ...FONTS.small,
    textTransform: 'capitalize',
    fontWeight: '700',
  },
  patientMetaRow: {
    flexDirection: 'row',
    gap: SIZES.sm,
    marginBottom: SIZES.sm,
  },
  metaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F2F6FD',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaBadgeText: {
    ...FONTS.small,
    color: '#4D5D7C',
  },
  patientActions: {
    flexDirection: 'row',
    gap: SIZES.sm,
  },
  actionBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  primaryActionBtn: {
    backgroundColor: '#EAF1FF',
  },
  secondaryActionBtn: {
    backgroundColor: '#E6F7F5',
  },
  primaryActionText: {
    ...FONTS.caption,
    color: '#1D4ED8',
    fontWeight: '700',
  },
  secondaryActionText: {
    ...FONTS.caption,
    color: '#0F766E',
    fontWeight: '700',
  },
  activityList: {
    gap: SIZES.sm,
    marginBottom: SIZES.lg,
  },
  quickActionsSection: {
    marginBottom: SIZES.lg,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: SIZES.md,
  },
  quickCard: {
    width: '48%',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: SIZES.md,
    borderWidth: 1,
    borderColor: '#EDF2FB',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  quickIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  quickLabel: {
    ...FONTS.caption,
    color: '#23345E',
    fontWeight: '700',
  },
});

export default styles;
