import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS } from '../../../constants/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFE',
  },
  gradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SIZES.lg,
    paddingTop: SIZES.lg,
    paddingBottom: SIZES.md,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: SIZES.radiusMedium,
    backgroundColor: COLORS.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    ...FONTS.h4,
    fontWeight: '700',
    color: COLORS.text,
  },
  notificationButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: 4,
    right: 4,
    borderRadius: 10,
    width: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: COLORS.white,
    fontSize: 10,
    fontWeight: '700',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SIZES.lg,
    paddingBottom: SIZES.xl,
  },
  welcomeSection: {
    marginBottom: SIZES.xl,
  },
  greeting: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    marginBottom: SIZES.xs / 2,
  },
  username: {
    ...FONTS.h2,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: SIZES.xs / 2,
  },
  role: {
    ...FONTS.body,
    color: COLORS.tutor,
    fontWeight: '600',
  },
  statsContainer: {
    flexDirection: 'row',
    gap: SIZES.md,
    marginBottom: SIZES.xl,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusLarge,
    padding: SIZES.md,
    alignItems: 'center',
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  statValue: {
    ...FONTS.h2,
    fontWeight: '800',
    marginTop: SIZES.xs,
    marginBottom: SIZES.xs / 2,
  },
  statLabel: {
    ...FONTS.small,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  section: {
    marginBottom: SIZES.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.md,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.sm,
  },
  sectionTitle: {
    ...FONTS.h4,
    fontWeight: '700',
  },
  seeAllText: {
    ...FONTS.caption,
    color: COLORS.primary,
    fontWeight: '600',
  },
  pcdCard: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusLarge,
    padding: SIZES.lg,
    marginBottom: SIZES.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  pcdHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.md,
  },
  pcdInfo: {
    flex: 1,
    marginLeft: SIZES.md,
  },
  pcdName: {
    ...FONTS.bodyBold,
    fontSize: 16,
    marginBottom: SIZES.xs / 2,
  },
  pcdDetail: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    marginBottom: SIZES.xs / 2,
  },
  pcdLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs / 2,
  },
  pcdLocationText: {
    ...FONTS.small,
    color: COLORS.info,
  },
  locationBtn: {
    width: 40,
    height: 40,
    borderRadius: SIZES.radiusMedium,
    backgroundColor: COLORS.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pcdStats: {
    flexDirection: 'row',
    gap: SIZES.lg,
    paddingTop: SIZES.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  pcdStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
  },
  pcdStatText: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
  },
  activitiesList: {
    gap: SIZES.sm,
  },
  quickActions: {
    flexDirection: 'row',
    gap: SIZES.md,
  },
  quickActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SIZES.sm,
    padding: SIZES.lg,
    borderRadius: SIZES.radiusLarge,
    backgroundColor: COLORS.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  quickActionText: {
    ...FONTS.bodyBold,
    color: COLORS.white,
    fontWeight: '700',
  },
  alertSection: {
    marginBottom: SIZES.xl,
  },
  alertTitle: {
    ...FONTS.h4,
    fontWeight: '700',
    color: COLORS.error,
  },
  alertCard: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusLarge,
    marginBottom: SIZES.sm,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.error,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  alertCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: SIZES.md,
    gap: SIZES.md,
  },
  alertIcon: {
    width: 40,
    height: 40,
    borderRadius: SIZES.radiusMedium,
    backgroundColor: COLORS.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertInfo: {
    flex: 1,
  },
  alertCardTitle: {
    ...FONTS.bodyBold,
    fontSize: 16,
    marginBottom: SIZES.xs / 2,
    color: COLORS.text,
  },
  alertCardMessage: {
    ...FONTS.caption,
    color: COLORS.error,
    fontWeight: '600',
    marginBottom: SIZES.xs / 2,
  },
  alertCardDistance: {
    ...FONTS.small,
    color: COLORS.textSecondary,
  },
});

export default styles;
