import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS } from '../../constants/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F8FF',
  },
  gradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(91, 155, 255, 0.20)',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SIZES.lg,
    paddingBottom: 90,
  },
  heroCard: {
    borderRadius: 22,
    padding: SIZES.lg,
    marginTop: SIZES.md,
    marginBottom: SIZES.md,
    shadowColor: '#0D3B8E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.md,
  },
  heroTitle: {
    ...FONTS.h3,
    color: COLORS.white,
    fontWeight: '700',
  },
  heroSubtitle: {
    ...FONTS.caption,
    color: '#DDEBFF',
  },
  heroAddButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#E2EEFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroStatItem: {
    alignItems: 'center',
  },
  heroStatValue: {
    ...FONTS.h4,
    color: COLORS.white,
    fontWeight: '800',
  },
  heroStatLabel: {
    ...FONTS.small,
    color: '#DDEBFF',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.sm,
    borderRadius: 14,
    gap: SIZES.sm,
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    ...FONTS.body,
    color: COLORS.text,
  },
  filtersContainer: {
    maxHeight: 50,
    marginTop: SIZES.md,
    marginBottom: SIZES.sm,
  },
  filtersContent: {
    gap: SIZES.sm,
  },
  filterChip: {
    paddingHorizontal: SIZES.md,
    paddingVertical: SIZES.sm,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#DDE6F6',
  },
  filterChipActive: {
    backgroundColor: '#1D4ED8',
    borderColor: '#1D4ED8',
  },
  filterChipText: {
    ...FONTS.caption,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  filterChipTextActive: {
    color: COLORS.white,
  },
  resultsCounter: {
    paddingVertical: SIZES.sm,
  },
  resultsText: {
    ...FONTS.caption,
    color: '#6C7891',
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SIZES.xl * 2,
  },
  emptyText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    marginTop: SIZES.md,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: SIZES.md,
    marginBottom: SIZES.md,
    borderWidth: 1,
    borderColor: '#E4ECFA',
    shadowColor: '#112147',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  cardInfo: {
    flex: 1,
    marginLeft: SIZES.md,
  },
  cardName: {
    ...FONTS.bodyBold,
    fontSize: 16,
    color: '#1B284A',
    marginBottom: 3,
  },
  especialidadBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EAF1FF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start',
    marginBottom: 3,
  },
  especialidadText: {
    ...FONTS.small,
    color: COLORS.professional,
    fontWeight: '700',
  },
  cardMatricula: {
    ...FONTS.small,
    color: '#63718D',
  },
  cardActions: {
    flexDirection: 'row',
    gap: SIZES.xs,
  },
  actionButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardDetails: {
    gap: SIZES.xs,
    marginBottom: SIZES.sm,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.sm,
  },
  detailText: {
    ...FONTS.caption,
    color: '#62708D',
    flex: 1,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: SIZES.sm,
    borderTopWidth: 1,
    borderTopColor: '#EDF2FB',
  },
  estadoBadge: {
    paddingHorizontal: SIZES.sm,
    paddingVertical: 4,
    borderRadius: 999,
  },
  estadoText: {
    ...FONTS.small,
    fontWeight: '700',
  },
  fab: {
    position: 'absolute',
    right: SIZES.lg,
    bottom: SIZES.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0D3B8E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 20, 38, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#D5DFEF',
    alignSelf: 'center',
    marginTop: SIZES.sm,
    marginBottom: SIZES.xs,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: SIZES.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#E8EEF8',
  },
  modalTitle: {
    ...FONTS.h4,
    fontWeight: '700',
    color: '#1A2752',
  },
  modalSubtitle: {
    ...FONTS.small,
    color: '#6A7895',
    marginTop: 2,
    maxWidth: 250,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F7FF',
  },
  modalForm: {
    padding: SIZES.lg,
  },
  formCard: {
    backgroundColor: '#F9FBFF',
    borderWidth: 1,
    borderColor: '#E4ECFA',
    borderRadius: 14,
    padding: SIZES.md,
    marginBottom: SIZES.md,
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
    marginBottom: SIZES.sm,
  },
  formSectionIcon: {
    width: 24,
    height: 24,
    borderRadius: 7,
    backgroundColor: '#EAF1FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formSectionTitle: {
    ...FONTS.bodyBold,
    color: '#1A2752',
  },
  formRow: {
    flexDirection: 'row',
    gap: SIZES.md,
  },
  formField: {
    flex: 1,
  },
  label: {
    ...FONTS.caption,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SIZES.xs,
    marginTop: SIZES.md,
  },
  input: {
    ...FONTS.body,
    borderWidth: 1,
    borderColor: '#DDE6F6',
    borderRadius: 12,
    padding: SIZES.md,
    backgroundColor: COLORS.white,
  },
  estadoSelector: {
    flexDirection: 'row',
    gap: SIZES.md,
    marginTop: SIZES.xs,
  },
  estadoOption: {
    flex: 1,
    paddingVertical: SIZES.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DDE6F6',
    alignItems: 'center',
  },
  estadoOptionActive: {
    backgroundColor: '#1D4ED8',
    borderColor: '#1D4ED8',
  },
  estadoOptionText: {
    ...FONTS.body,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  estadoOptionTextActive: {
    color: COLORS.white,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: SIZES.md,
    marginTop: SIZES.xl,
    marginBottom: SIZES.lg,
    paddingTop: SIZES.md,
    borderTopWidth: 1,
    borderTopColor: '#E8EEF8',
  },
  modalButton: {
    flex: 1,
  },
});

export default styles;
